### ISSUE TITLE
Segmentation_Failed & Bus Error

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#33]
There is two bugs.. 
https://cloud.orange.ro/share/ab269ecdde8864db1cff48268b71b3ab09daa7984b474901
![captura de ecran din 2017-05-18 19-15-45](https://cloud.githubusercontent.com/assets/10581339/26212623/cf9ee5ba-3bfe-11e7-8708-a6b880f456c2.png)
 First is screenrecorded, second is screenshoted..

**Comment by pjasicek** [comment]
Damn... thank you for the report. I will have fix within a couple of minutes I think.

**Comment by pjasicek** [comment]
Fixed with 1b6f79796c67cee0fb71024bf318f91e46576dc8

Retesting it would be most appreciated.

**Comment by denispapec** [comment]
I can still reproduce issue with https://github.com/pjasicek/CaptainClaw/commit/1b6f79796c67cee0fb71024bf318f91e46576dc8 commit ![screenshot-2017-05-18_19 04 00](https://cloud.githubusercontent.com/assets/5442891/26216774/35bae5e4-3bfd-11e7-85b2-87b623776b1a.png)

**Comment by pjasicek** [comment]
I don't have this problem under Windows, that's unfortunate... does it happen every time in the score screen or just at certain times / certain points in score screen state ?

**Comment by denispapec** [comment]
Every time at same moment when Claw collects map.

**Comment by pjasicek** [comment]
Try it with 0ab439a5cf0111f0062adb6cc8b3a5cacee83203 pleasse

**Comment by denispapec** [comment]
Issue still exists at same moment.

![screenshot-2017-05-18_19 43 36](https://cloud.githubusercontent.com/assets/5442891/26218318/73f334d8-3c02-11e7-9038-b5e0026c71eb.png)

**Comment by pjasicek** [comment]
Too bad I uninstalled my linux distro... I will try it in virtualbox with ubuntu, since this is just a guessing game for me.

**Comment by pjasicek** [comment]
Please try it with 36418fe084dd6baa73d9517630f1459e11c2388e so I know for sure that it is caused somewhere in initializing the score screen. Thank you.

**Comment by denispapec** [comment]
Ok, i tried to restart Arch and now seems to work, and loads into level 2 after score screen... i guess some of previous segmentation fault affected memory at that point and kept failing.

**Comment by pjasicek** [comment]
Great to hear ! At least this made me install Linux VM for future cases. I will test this anyway under Ubutnu 17.04.

**Comment by denispapec** [comment]
```[GAME LOADING]: Elapsed microseconds: 1874894
INFO: Changing to: 3
INFO: Aborting event processing; time ran out
INFO: Changing to: 4
ERROR: [AmmoUpdatedDelegate] Unknown ammo type: 1
ERROR: [AmmoUpdatedDelegate] Unknown ammo type: 2
ERROR: [SetCurrentPhysicsState] Unknown physics state. Assume falling
ERROR: [SetCurrentPhysicsState] Unknown physics state. Assume falling
ERROR: [SetCurrentPhysicsState] Unknown physics state. Assume falling
[1]    8054 segmentation fault (core dumped)  ./captainclaw
```
Happened again, not sure if it's my machine or bug...

**Comment by pjasicek** [comment]
Yes it also happened on Ubuntu VM. Pretty annoying thing is that when I run it in GDB it does not crash.

**Comment by pjasicek** [comment]
Could you please try to run it in gdb ?

gdb ./captainclaw
(gdb) run

**Comment by denispapec** [comment]
Yeah,

```[GAME LOADING]: Elapsed microseconds: 1805307
INFO: Changing to: 3
INFO: Aborting event processing; time ran out
INFO: Changing to: 4
[New Thread 0x7fffc6b25700 (LWP 31462)]
[Thread 0x7fffc6b25700 (LWP 31462) exited]
ERROR: [AmmoUpdatedDelegate] Unknown ammo type: 1
ERROR: [AmmoUpdatedDelegate] Unknown ammo type: 2
[New Thread 0x7fffc6b25700 (LWP 32377)]
[Thread 0x7fffc6b25700 (LWP 32377) exited]
ERROR: [SetCurrentPhysicsState] Unknown physics state. Assume falling
[New Thread 0x7fffc6b25700 (LWP 775)]
[Thread 0x7fffc6b25700 (LWP 775) exited]
WARN: [RemoveOverlappingGround] Could not remove overlapping ground - no such fixture found

Thread 1 "captainclaw" received signal SIGSEGV, Segmentation fault.
__gnu_cxx::__atomic_add_dispatch (__val=1, __mem=0x10e) at /usr/include/c++/6.3.1/ext/atomicity.h:96
96	      __atomic_add(__mem, __val);
(gdb) 
```

**Comment by pjasicek** [comment]
`(gdb) bt
#0  __gnu_cxx::__atomic_add_dispatch (__val=1, __mem=0x7fff00000084) at /usr/include/c++/6/ext/atomicity.h:96
#1  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy (this=0x7fff0000007c) at /usr/include/c++/6/bits/shared_ptr_base.h:134
#2  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count (__r=..., this=<synthetic pointer>) at /usr/include/c++/6/bits/shared_ptr_base.h:669
#3  std::__shared_ptr<Actor, (__gnu_cxx::_Lock_policy)2>::__shared_ptr (this=<synthetic pointer>) at /usr/include/c++/6/bits/shared_ptr_base.h:926
#4  std::shared_ptr<Actor>::shared_ptr (this=<synthetic pointer>) at /usr/include/c++/6/bits/shared_ptr.h:107
#5  std::pair<unsigned int const, std::shared_ptr<Actor> >::pair (this=<synthetic pointer>) at /usr/include/c++/6/bits/stl_pair.h:288
#6  BaseGameLogic::UnloadLevel (this=this@entry=0x5555562bb120) at /home/osboxes/CaptainClaw/CaptainClaw/Engine/GameApp/BaseGameLogic.cpp:1111
#7  0x000055555567315a in BaseGameLogic::FinishedLevelDelegate (this=0x5555562bb120, pEventData=...)
    at /home/osboxes/CaptainClaw/CaptainClaw/Engine/GameApp/BaseGameLogic.cpp:948
#8  0x000055555565f4db in fastdelegate::FastDelegate1<std::shared_ptr<IEventData>, void>::operator() (p1=..., this=<synthetic pointer>)
    at /home/osboxes/CaptainClaw/./ThirdParty/FastDelegate/FastDelegate.h:991
#9  EventMgr::VUpdate (this=0x555555997300, maxMillis=20) at /home/osboxes/CaptainClaw/CaptainClaw/Engine/Events/EventMgrImpl.cpp:242
#10 0x00005555556664b8 in BaseGameApp::Run (this=0x555555977f60 <testApp>) at /home/osboxes/CaptainClaw/CaptainClaw/Engine/GameApp/BaseGameApp.cpp:217
#11 0x000055555567ab04 in RunGameEngine (argc=1, argv=0x7fffffffdfc8) at /home/osboxes/CaptainClaw/CaptainClaw/Engine/GameApp/MainLoop.cpp:33
#12 0x00007ffff63c23f1 in __libc_start_main (main=0x5555555d7ad0 <main(int, char**)>, argc=1, argv=0x7fffffffdfc8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdfb8) at ../csu/libc-start.c:291
#13 0x00005555555da0ea in _start ()`

**Comment by pjasicek** [comment]
Thanks, luckily I now know how to reproduce it. 

1) Load level 1 at 2nd checkpoint
2) Go the normal route without cheats till end
3) Crash

**Comment by denispapec** [comment]
Ah! Indeed, i didn't think it mattered how level was loaded :smile:

**Comment by pjasicek** [comment]
https://pastebin.com/iaAhet2a

Now to figure out why destroying Catnip crashes the game, jesus

**Comment by pjasicek** [comment]
I most likely know where the problem is and how to fix it, but I will dig into it tomorrow.

**Comment by cipiricus** [comment]
Ok...I'm sorry because I don't tested the game earlier, I have some personal problems :/

**Comment by pjasicek** [comment]
Fixed with 4e55074f4fe3629f31e05596e3e15ca19d79c2dd

Works on Ubuntu 17.04. I Would appreciate if you could also confirm this :)

Thanks again to both of you, your help is really appreciated.

**Comment by cipiricus** [comment]
I can confirm proudly..the score screen works again... thanks a lot :1st_place_medal:

**Comment by cipiricus** [comment]
pjasicek, i looked at the code and I sawed something interesting, about cutscenes, I maded some researches and there exist some cutscenes in .vbo format

**Comment by pjasicek** [comment]
Yea, I know about that, I also found them ripped with XViD codec (with that they have about 28MB). But the problem is that I dont have any built in solution of how to play videos (cutscenes) - SDL2 does not support this out of the box, I would have to integrate some other library like ffmpeg, which would be really taxing for me at the moment. Maybe in future I will implement it.

**Comment by cipiricus** [comment]
I understand, anyway cutscenes for now isn't important, that can wait, important is I think is the game, boss logics and maps
